print("   A        B B B B        C C C       D D D D ")
print(" A   A      B      B      C     C      D      D")
print("A     A     B      B      C            D      D")
print("A A A A     B B B B       C            D      D")
print("A     A     B      B      C            D      D")
print("A     A     B      B      C     C      D      D")
print("A     A     B B B B        C C C       D D D D")
print("")
print("")
print("E E E E E   F F F F F       G G G      H       H")
print("E           F             G       G    H       H")
print("E           F             G            H       H")
print("E E E       F F F         G   G G G    H H H H H")
print("E           F             G       G    H       H")
print("E           F             G       G    H       H")
print("E E E E E   F               G G G      H       H")